### ISSUE TITLE
client.send() support

### ISSUE THREAD

**Issue by romuloctba** [hugoviktor/nestjs-stan-transport#3]
Hi @hugoviktor , thanks for this.

I would like to know if you plan to support `client.send()` for the `@MessagePattern`?

If not, do you think is possible to do it? And could I try and PR here?

Thanks a lot!

**Comment by hugoviktor** [comment]
Hi, @romuloctba, thanks to contact me.
I am currently planning support for @MessagePattern, I plan to release it in the next few weeks.(not developing now), if you can do it, feel free to contribute, and send a PR.

**Comment by romuloctba** [comment]
Hey @hugoviktor , glad to know that! I will give it a try, but make no promises :)

Hope to raise a PR soon, but still need to understand what is needed to implement the @MessagePattern. I plan to read trough the 3 part series: https://dev.to/nestjs/integrate-nestjs-with-external-services-using-microservice-transporters-part-1-p3

Thanks again!

**Comment by romuloctba** [comment]
[Further research](https://github.com/nats-io/stan.js/issues/29#issuecomment-270487642) shows me we might need to use the standard nats for the request/reply scenario

**Comment by romuloctba** [comment]
So, I am thinking here, maybe the easier way is to use the module.providers to expose a NATS-only client that can be used to the request reply pattern

But not sure if would be an overhead, since user still need to 'connectMicroservices' at main.ts

**Comment by romuloctba** [comment]
I will close this, for as I learned, the client.send will not work for nats streaming as per design.
To use client.send, nats must be leverage, without the streaming capabilities, for its req, res, pattern.
